version: 2.1
orbs:
  node: circleci/node@5.1.0
  #heroku: circleci/heroku@1.2.6 (whatever the host is)

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
        command: yarn test
        name: Run tests
      - run:
          command: yarn build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

deploy: 
  executor: #heroku/defualt
  steps:
    -attach_workspace:
      at: ~/project
  # - heroku/deploy-via-git:
      # force: true

workflows:
  test_my_app:
    jobs:
      - build_and_test
      -deploy:
        requires:
          - build_and_tes
        filters: 
          branches:
            only: main
